# Lab 1: Numerical Computations with Python

## Part 2. Explore Numpy Arrays and Metrices

### 1D Arrays

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print a

b = np.array([0.1, 0.2, 0.3])
print b

[1 2 3]
[ 0.1  0.2  0.3]


In [3]:
# Arrays elements are indexed from 0 to n-1, where n is the number of elements
for i in range(len(b)):
    print i, b[i]

0 0.1
1 0.2
2 0.3


In [4]:
# Operations - corresponds to each indivisual index
print 0.5 * a
print a + b
print a - b
print a * b

[ 0.5  1.   1.5]
[ 1.1  2.2  3.3]
[ 0.9  1.8  2.7]
[ 0.1  0.4  0.9]


In [5]:
# It is identical to a+b
c = np.zeros(3)
for i in range(len(c)):
    c[i] = a[i] + b[i]
print c

[ 1.1  2.2  3.3]


### 2D Arrays

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print a

b = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print b

[[1 2 3]
 [4 5 6]]
[[ 0.1  0.2  0.3]
 [ 0.4  0.5  0.6]]


In [9]:
# Get an element
print a[1, 2]

6


In [11]:
# Get a row
print a[1,:]

[4 5 6]


In [12]:
# Operations - corresponds to each indivisual index
print 0.5 * a
print a + b
print a - b
print a * b

[[ 0.5  1.   1.5]
 [ 2.   2.5  3. ]]
[[ 1.1  2.2  3.3]
 [ 4.4  5.5  6.6]]
[[ 0.9  1.8  2.7]
 [ 3.6  4.5  5.4]]
[[ 0.1  0.4  0.9]
 [ 1.6  2.5  3.6]]


### Matrices

In [13]:
a = np.matrix([[1, 2, 3], [4, 5, 6]])
print a

b = np.matrix([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print b

[[1 2 3]
 [4 5 6]]
[[ 0.1  0.2  0.3]
 [ 0.4  0.5  0.6]]


In [14]:
# Operations - matrix operations
print 0.5 * a
print a + b
print a - b

[[ 0.5  1.   1.5]
 [ 2.   2.5  3. ]]
[[ 1.1  2.2  3.3]
 [ 4.4  5.5  6.6]]
[[ 0.9  1.8  2.7]
 [ 3.6  4.5  5.4]]


In [15]:
# Invalid cross-product operation due to incompatible size
print a * b

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [16]:
# Valid cross-product operation
c = np.matrix([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]])
print "shape a: ", a.shape
print "shape c: ", c.shape
print a * c

shape a:  (2, 3)
shape c:  (3, 2)
[[ 2.2  2.8]
 [ 4.9  6.4]]


### Special Arrays

In [18]:
# Array with arbitrary values
print np.empty([2, 3])

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [19]:
# With ones along diagonal and zeros elsewhere
print np.eye(2, 3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]]


In [20]:
# Identity arry
print np.identity(3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [21]:
# Array fills with ones
print np.ones([2, 3])

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [22]:
# Array fills with zeros
print np.zeros([2, 3])

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [25]:
# Array fills with random values
print np.random.rand(2, 3)

[[ 0.80752948  0.90011752  0.69294322]
 [ 0.03440712  0.04823819  0.77020036]]


In [26]:
# Convert 2D arrays into matrices
a = np.identity(3)
print a

b = np.matrix(a)
print b

# Short hand method
print np.matrix(np.identity(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Part 3. Systems of Linear Equations

### System of Well-determined Linear Equations

A system of linear equations such as
```
 x + y + z = 2
 2x + z = 1
 x + 2y + z = 3
```
can be written as
```
 Ax = b
```

There are three independent equations with three unknown. So, the unknown can be solved by computing
```
 x = A^(-1) b
```

In [33]:
# To solve x
import numpy as np
import numpy.linalg as la

A = np.matrix([[1, 1, 1], [2, 0, 1], [1, 2, 1]])
print "A = \n", A

b = np.matrix([[2], [1], [3]])
print "b = \n", b

x = la.inv(A) * b
print "\nUsing la.inv(A) * b"
print "x = \n", x
print "A * x = \n", A * x

# Short-hand method
x = la.solve(A, b)
print "\nUsing la.solve(A, b)"
print "x = \n", x

A = 
[[1 1 1]
 [2 0 1]
 [1 2 1]]
b = 
[[2]
 [1]
 [3]]

Using la.inv(A) * b
x = 
[[ 0.]
 [ 1.]
 [ 1.]]
A * x = 
[[ 2.]
 [ 1.]
 [ 3.]]

Using la.solve(A, b)
x = 
[[ 0.]
 [ 1.]
 [ 1.]]


### System of Over-determined Equations